=== OPENER-next/OPENER-next/assets/datasets/map_feature_collection_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "OSM map feature collection",
  "description": "A list of OSM map feature templates, each with an additional visual and textual representation.",
  "type": "array",
  "items": {
    "type": "object",
    "description": "A map feature template.",
    "required": [ "name", "icon", "osm_tags", "osm_element" ],
    "additionalProperties": false,
    "properties": {
      "name": {
        "description": "A label describing this map feature.",
        "type": "string"
      },
      "icon": {
        "description": "The icon name/identifier from the custom icons map.",
        "type": "string"
      },
      "osm_tags": {
        "type": "object",
        "description": "A key value map of OSM tags that define that osm feature.",
        "additionalProperties": {
          "description": "If this is set to a boolean the corresponding osm tag either needs to exist or not independent of its value. An array means one of the given values must match the tag value.",
          "type": ["string", "boolean", "array"],
          "items": {
            "type": ["string", "boolean"]
          },
          "minItems": 1
        }
      },
      "osm_element": {
        "description": "A single OSM element or list of elements. An array means one of the given elements must match.",
        "anyOf": [
          {
            "$ref": "#/definitions/osm_element_type"
          },
          {
            "type": "array",
            "items": {
              "$ref": "#/definitions/osm_element_type"
            },
            "minItems": 1
          }
        ]
      }
    }
  },
  "definitions": {
    "osm_element_type": { "enum": ["Node", "OpenWay", "ClosedWay", "Relation"] }
  }
}

=== OPENER-next/OPENER-next/assets/osm_objects.json
[
  {
    "name": "Plattform",
    "icon":  "platform",
    "osm_tags": {
      "public_transport": "platform"
    },
    "osm_element": "Node"
  },
  {
    "name": "Bus",
    "icon":  "bus",
    "osm_tags": {
      "bus": "yes"
    },
    "osm_element": "Node"
  },
  {
    "name": "Train",
    "icon":  "train",
    "osm_tags": {
      "train": "yes"
    },
    "osm_element": "Node"
  },
  {
    "name": "Fahrtkartenverkaufsstelle",
    "icon":  "ticket_shop",
    "osm_tags": {
      "shop": "ticket",
      "tickets:public_transport": "yes"
    },
    "osm_element": "Node"
  },
  {
    "name": "Informationsstelle",
    "icon":  "information",
    "osm_tags": {
      "tourism": "information",
      "information": "office"
    },
    "osm_element": "Node"
  },
  {
    "name": "Fahrkartenautomat",
    "icon":  "vending_machine",
    "osm_tags": {
      "amenity": "vending_machine",
      "vending": "public_transport_tickets"
    },
    "osm_element": "Node"
  },
  {
    "name": "Parkplatz",
    "icon":  "parking",
    "osm_tags": {
      "amenity": "parking",
      "access": "yes"
    },
    "osm_element": "Node"
  },
  {
    "name": "Parkplatz",
    "icon":  "parking",
    "osm_tags": {
      "amenity": "parking",
      "access": "yes"
    },
    "osm_element": "ClosedWay"
  },
  {
    "name": "Taxi-Stand",
    "icon":  "taxi",
    "osm_tags": {
      "amenity": "taxi"
    },
    "osm_element": "Node"
  },
  {
    "name": "Toiletten",
    "icon":  "toilet",
    "osm_tags": {
      "amenity": "toilets",
      "access": "yes"
    },
    "osm_element": "Node"
  },
  {
    "name": "Aufbewahrungsmöglichkeiten",
    "icon":  "locker",
    "osm_tags": {
      "amenity": "luggage_locker"
    },
    "osm_element": "Node"
  },
  {
    "name": "Gepäcktransport",
    "icon":  "bag",
    "osm_tags": {
      "amenity": "trolley_bay"
    },
    "osm_element": "Node"
  },
  {
    "name": "Informationssäule",
    "icon":  "terminal",
    "osm_tags": {
      "tourism": "information",
      "information": "terminal"
    },
    "osm_element": "Node"
  },
  {
    "name": "Kombinierte Informations- und Notrufsäule",
    "icon":  "terminal",
    "osm_tags": {
      "emergency": "phone",
      "tourism": "information",
      "information": "terminal"
    },
    "osm_element": "Node"
  },
  {
    "name": "Notrufsäule",
    "icon": "phone",
    "osm_tags": {
      "emergency": "phone"
    },
    "osm_element": "Node"
  }
]

=== OPENER-next/OPENER-next/assets/osm_elements.json
[
  {
    "name": "Fahrtkartenverkaufsstelle",
    "icon":  "ticket_shop",
    "osm_tags": {
      "shop": "ticket",
      "tickets:public_transport": "yes"
    },
    "osm_element": "Node"
  },
  {
    "name": "Informationsstelle",
    "icon":  "ticket_shop",
    "osm_tags": {
      "tourism": "information",
      "information": "office"
    },
    "osm_element": "Node"
  },
  {
    "name": "Fahrkartenautomat",
    "icon":  "ticket_shop",
    "osm_tags": {
      "amenity": "vending_machine",
      "vending": "public_transport_tickets"
    },
    "osm_element": "Node"
  },
  {
    "name": "Parkplatz",
    "icon":  "ticket_shop",
    "osm_tags": {
      "amenity": "parking",
      "access": "yes"
    },
    "osm_element": ["Node",  "ClosedWay"]
  },
  {
    "name": "Taxi-Stand",
    "icon":  "ticket_shop",
    "osm_tags": {
      "amenity": "taxi"
    },
    "osm_element": "Node"
  },
  {
    "name": "Toiletten",
    "icon":  "ticket_shop",
    "osm_tags": {
      "amenity": "toilets",
      "access": "yes"
    },
    "osm_element": "Node"
  },
  {
    "name": "Aufbewahrungsmöglichkeiten",
    "icon":  "ticket_shop",
    "osm_tags": {
      "amenity": "luggage_locker"
    },
    "osm_element": "Node"
  },
  {
    "name": "Gepäcktransport",
    "icon":  "ticket_shop",
    "osm_tags": {
      "amenity": "trolley_bay"
    },
    "osm_element": "Node"
  },
  {
    "name": "Informationssäule",
    "icon":  "ticket_shop",
    "osm_tags": {
      "tourism": "information",
      "information": "terminal"
    },
    "osm_element": "Node"
  },
  {
    "name": "Kombinierte Informations- und Notrufsäule",
    "icon":  "ticket_shop",
    "osm_tags": {
      "emergency": "phone",
      "tourism": "information",
      "information": "terminal"
    },
    "osm_element": "Node"
  },
  {
    "name": "Notrufsäule",
    "image": "ticket_shop",
    "osm_tags": {
      "emergency": "phone"
    },
    "osm_element": "Node"
  }
]
