=== OPENER-next/OPENER-next/assets/datasets/question_catalog_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Question Catalog",
  "description": "A list of questions.",
  "type": "array",
  "items": {
    "type": "object",
    "description": "A question derived from the DELFI catalog.",
    "properties": {
      "id": {
        "description": "The DELFI id this question is derived from.",
        "type": "integer",
        "exclusiveMinimum": 0
      },
      "name": {
        "description": "A short title providing additional context to this question.",
        "type": "string"
      },
      "description": {
        "description": "Details or further information describing this question.",
        "type": "string"
      },
      "image": {
        "description": "A list of image urls that may help to clarify this question.",
        "type": "array",
        "items": {
          "type": "string",
          "format": "uri-reference"
        },
        "minItems": 1
      },
      "question": {
        "description": "The actual question. It should be kept as short as possible while still being comprehensible and independent of the context in which it is asked.",
        "type": "string"
      },
      "input": {
        "type": "object",
        "description": "This holds properties specifying the UI input element and its constraints.",
        "properties": {
          "type": {
            "description": "The value type of the answer. This is closely related to the widget that will be displayed to the end user.",
            "enum": ["Bool", "Number", "String", "List", "Duration", "OpeningHours"]
          },
          "values": {
            "description": "A map of values with additional information for the user and the corresponding OSM tags.",
            "type": "object",
            "additionalProperties": {
              "type": "object",
              "properties": {
                "osm_tags": {
                  "type": "object",
                  "additionalProperties": {
                    "type": "string"
                  }
                },
                "name": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                },
                "image": {
                  "type": "string",
                  "format": "uri-reference"
                },
                "unit": {
                  "description": "An optional unit that will be displayed to the user.",
                  "type": "string"
                },
                "min": {
                  "type": "integer"
                },
                "max": {
                  "type": "integer"
                },
                "decimals": {
                  "description": "An optional property to specify how many decimals are allowed for type Number.",
                  "type": "integer",
                  "minimum": 0
                }
              },
              "additionalProperties": false
            }
          }
        },
        "additionalProperties": false,
        "required": [ "type", "values" ]
      },
      "conditions": { "$ref": "osm_condition_schema.json" },
      "isProfessional": {
        "description": "Certain questions seek for information that requires authorization or might be dangerous to collect. If omitted this will fallback to false.",
        "type": "boolean",
        "default": false
      }
    },
    "additionalProperties": false,
    "required": [ "id", "name", "question", "input" ]
  }
}

=== OPENER-next/OPENER-next/assets/datasets/question_catalog.json
[
   {
      "id": 1021,
      "name": "Betreiber",
      "question": "Welches Verkehrsunternehmen betreibt die Fahrkartenverkaufsstelle?",
      "description": "Bei Verkaufsstellen handelt es sich um Einrichtungen, die Fahrkarten verkaufen (z.B. offizielle Vertriebsstellen der Verkehrsunternehmen oder des Verbundgebietes). Die Verkaufsstellen sind i.d.R. mit einem Erkennungszeichen (Tafel, Wimpel, Aufkleber, etc.) ausgestattet.",
      "input": {
         "type": "String",
         "values": {
            "single": {
               "name": "Betreiber",
               "osm_tags": {
                  "operator": "%s"
               }
            }
         }
      },
      "conditions": [
         {
            "osm_tags": {
               "shop": "ticket",
               "tickets:public_transport": "yes",
               "operator": false
            }
         }
      ]
   },
   {
      "id": 1022,
      "name": "Rollstuhlgerecht",
      "question": "Ist die Fahrkartenverkaufsstelle rollstuhlgerecht?",
      "description": "Rollstuhlgerecht bedeutet, die Fahrkartenverkaufsstelle ist stufenfrei erreichbar und die Zugänge haben eine ausreichende Breite (≥90cm).",
      "input": {
         "type": "Bool",
         "values": {
            "true": {
               "osm_tags": {
                  "wheelchair": "yes"
               }
            },
            "false": {
               "osm_tags": {
                  "wheelchair": "no"
               }
            }
         }
      },
      "conditions": [
         {
            "osm_tags": {
               "shop": "ticket",
               "tickets:public_transport": "yes",
               "wheelchair": false
            }
         }
      ]
   },
   {
      "id": 1031,
      "name": "Betreiber",
      "question": "Welches Verkehrsunternehmen betreibt die Informationsstelle?",
      "input": {
         "type": "String",
         "values": {
            "single": {
               "name": "Betreiber",
               "osm_tags": {
                  "operator": "%s"
               }
            }
         }
      },
      "conditions": [
         {
            "osm_tags": {
               "tourism": "information",
               "information": "office",
               "information:public_transport": "yes",
               "operator": false
            }
         }
      ]
   },
   {
      "id": 1032,
      "name": "Rollstuhlgerecht",
      "question": "Ist die Informationsstelle rollstuhlgerecht?",
      "description": "Rollstuhlgerecht bedeutet, die Informationsstelle ist stufenfrei erreichbar und die Zugänge haben eine ausreichende Breite (≥90cm).",
      "input": {
         "type": "Bool",
         "values": {
            "true": {
               "osm_tags": {
                  "wheelchair": "yes"
               }
            },
            "false": {
               "osm_tags": {
                  "wheelchair": "no"
               }
            }
         }
      },
      "conditions": [
         {
            "osm_tags": {
               "tourism": "information",
               "information": "office",
               "information:public_transport": "yes",
               "wheelchair": false
            }
         }
      ]
   },
   {
      "id": 1051,
      "name": "Parkplatzart",
      "question": "Um welche Parkplatzart handelt es sich?",
      "input": {
         "type": "List",
         "values": {
            "surface": {
               "name": "Ebenerdiger Parkplatz",
               "image": "packages/nvbw_open_data/photos/1051a.jpg",
               "osm_tags": {
                  "parking": "surface"
               }
            },
            "underground": {
               "name": "Tiefgarage",
               "image": "packages/nvbw_open_data/photos/1051b.jpg",
               "osm_tags": {
                  "parking": "underground"
               }
            },
            "street_side": {
               "name": "Parkbucht",
               "image": "packages/nvbw_open_data/photos/1051c.jpg",
               "osm_tags": {
                  "parking": "street_side"
               }
            },
            "multi-storey": {
               "name": "Parkhaus",
               "image": "packages/nvbw_open_data/photos/1051d.jpg",
               "osm_tags": {
                  "parking": "multi-storey"
               }
            }
         }
      },
      "conditions": [
         {
            "osm_tags": {
               "amenity": "parking",
               "access": [
                  "yes",
                  "customers",
                  false
               ],
               "parking": false
            }
         }
      ]
   },
   {
      "id": 1051,
      "name": "Behindertenparkplätze",
      "question": "Gibt es gesonderte Parkplätze für behinderte Personen?",
      "image": [
         "packages/nvbw_open_data/photos/1051e.jpg",
         "packages/nvbw_open_data/photos/1051f.jpg",
         "packages/nvbw_open_data/photos/1051g.jpg"
      ],
      "input": {
         "type": "Bool",
         "values": {
            "true": {
               "osm_tags": {
                  "capacity:disabled": "yes"
               }
            },
            "false": {
               "osm_tags": {
                  "capacity:disabled": "no"
               }
            }
         }
      },
      "conditions": [
         {
            "osm_tags": {
               "amenity": "parking",
               "access": [
                  "yes",
                  "customers",
                  false
               ],
               "capacity:disabled": false
            }
         }
      ]
   },
   {
      "id": 1051,
      "name": "Anzahl an Behindertenparkplätzen",
      "question": "Wie viele Parkplätze für behinderte Personen gibt es?",
      "description": "Behindertenparkplätze sind eigene Parkmöglichkeiten für behinderte Personen und weisen i.d.R. geräumigere Stellplatzmaße auf. Behindertenparkplätze sind durch ein Zusatzschild mit dem Piktogramm eines Rollstuhlfahrers gekennzeichnet. Zusätzlich sind meist Bodenmarkierungen angebracht.",
      "input": {
         "type": "Number",
         "values": {
            "single": {
               "name": "Parkplatzanzahl",
               "decimals": 0,
               "min": 1,
               "max": 1000,
               "osm_tags": {
                  "capacity:disabled": "%s"
               }
            }
         }
      },
      "conditions": [
         {
            "osm_tags": {
               "amenity": "parking",
               "access": [
                  "yes",
                  "customers",
                  false
               ],
               "capacity:disabled": "yes"
            }
         }
      ]
   },
   {
      "id": 1052,
      "name": "Park+Ride",
      "question": "Ist dies ein Park+Ride-Parkplatz?",
      "description": "Park+Ride-Anlagen sind Parkplätze mit Anbindung an öffentliche Verkehrsmittel, die es Personen ermöglichen, ihr Fahrzeug zu verlassen und für den Rest der Reise auf öffentliche Verkehrsmittel umzusteigen.",
      "image": [
         "packages/nvbw_open_data/photos/1052a.jpg",
         "packages/nvbw_open_data/photos/1052b.jpg",
         "packages/nvbw_open_data/photos/1052c.jpg"
      ],
      "input": {
         "type": "Bool",
         "values": {
            "true": {
               "osm_tags": {
                  "park_ride": "yes"
               }
            },
            "false": {
               "osm_tags": {
                  "park_ride": "no"
               }
            }
         }
      },
      "conditions": [
         {
            "osm_tags": {
               "amenity": "parking",
               "access": [
                  "yes",
                  "customers",
                  false
               ],
               "park_ride": false
            }
         }
      ]
   },
   {
      "id": 1052,
      "name": "Parkplatzgebühren",
      "question": "Fallen für das Parken Gebühren an?",
      "input": {
         "type": "Bool",
         "values": {
            "true": {
               "osm_tags": {
                  "fee": "yes"
               }
            },
            "false": {
               "osm_tags": {
                  "fee": "no"
               }
            }
         }
      },
      "conditions": [
         {
            "osm_tags": {
               "amenity": "parking",
               "access": [
                  "yes",
                  "customers",
                  false
               ],
               "fee": false
            }
         }
      ]
   },
   {
      "id": 1071,
      "name": "Toiletten-Zugänglichkeit",
      "question": "Für wen sind die Toiletten zugänglich?",
      "input": {
         "type": "List",
         "values": {
            "only": {
               "name": "Ausschließlich für Rollstuhlfahrende",
               "description": "Die Toiletten sind nur für Rollstuhlfahrende vorgesehen.",
               "osm_tags": {
                  "wheelchair": "designated"
               }
            },
            "yes": {
               "name": "Für Rollstuhlfahrende und andere",
               "description": "Die Toiletten sind für Rollstuhlfahrende und andere Personen vorgesehen.",
               "osm_tags": {
                  "wheelchair": "yes"
               }
            },
            "no": {
               "name": "Nicht für Rollstuhlfahrende",
               "description": "Die Toiletten sind nicht rollstuhlgerecht. Rollstuhlfahrernde haben keine Zugangsmöglichkeiten.",
               "osm_tags": {
                  "wheelchair": "no"
               }
            }
         }
      },
      "conditions": [
         {
            "osm_tags": {
               "amenity": "toilets",
               "access": [
                  "yes",
                  false
               ],
               "wheelchair": false
            }
         }
      ]
   },
   {
      "id": 1073,
      "name": "Toiletten nur mit Schlüssel zugänglich",
